AlmaLinux/albs-web-server

- README.md
> README info

- alws/crud.py
- Added deleting binary and source rpms before artifacts
- Added try/except block for pulp_client.remove_artifact
> ALBS-52: Fixed a few bugs for deleting build

- alws/crud.py
- alws/routers/builds.py
- Added verbose error if build is released or not found
- Added deleting build refs and linked builds
> ALBS-82: Fixes a few bugs for deleting build

- alws/crud.py
- alws/routers/builds.py
- alws/routers/users.py
- alws/schemas/build_schema.py
- alws/utils/pulp_client.py
- Added logic for searching builds
- Added new schema for search filters
- Added new endpoint for getting all users from DB
- Added new PULP endpoint for search builds by NEVRA
> ALBS-24: Added functional for searching builds

- alws/config.py
- alws/releases.py
- alws/utils/beholder_client.py
Add repository ID to response from backend for release. Fixed communication with beholder service
> ALBS-84 Repository ID for release response. Beholder communication

- .gitignore
- reference_data/platforms.yaml
We need to build almalinux-9-beta, so I tried to add a platform
I'm not sure that all is right.
> Add almalinux-9 platform

- reference_data/platforms.yaml
Add devel repositories for almalinux-9 platform
Add javapackages-tools:201902 module for bootstrap
> Javapackages-tools repo for a8 and devel repos for a9

- alws/constants.py
- alws/crud/test.py
- alws/routers/tests.py
- alws/schemas/test_schema.py
- alws/utils/file_utils.py
- alws/utils/parsing.py
- requirements.txt
- tests/test_crud/test_test.py
- tests/test_utils/test_parsing.py
Acceptance criteria:
- parsing test system logs by tap.py, 
- sending them to UI, 
- write documentation,
- write tests.
> ALBS-114 Test System logs parsing for UI

- reference_data/platforms.yaml
> Update AlmaLinux 8 PPC URLs to stable

- alws/crud/sign_task.py
- alws/utils/pulp_client.py
Fixed sign task completion if some artifacts are matching already created packages
> Fixed sign task completion

- alws/crud/build_node.py
- alws/models.py
- alws/utils/modularity.py
- alws/utils/multilib.py
Reverts AlmaLinux/albs-web-server#194
> Revert "Module artifacts fixes"

- alws/build_planner.py
- alws/schemas/build_schema.py
- alws/utils/multilib.py
This commit fixes partial modules update: do not add artifacts that are
not related to each requested architecture
> Fixed partial modules update

- alws/app.py
- alws/routers/builds.py
- alws/routers/platforms.py
- alws/routers/sign_task.py
- alws/routers/tests.py
- alws/routers/users.py
It's paired with this pr to make anonymous public access for build system: https://github.com/AlmaLinux/albs-frontend/pull/189
> Made some endpoints public to enable read-only access to the system

- reference_data/platforms.yaml
- Update path to javapackages-tools for ppc64le arch
- Add s390x arch to arch list
- Add s390x repositories
> s390x for AlmaLinux8

- alws/app.py
- alws/config.py
- alws/release_planner.py
Also, added some logging to release_planner.py
> ALBS-398: Added configurable setting logging_level

- alws/crud/build.py
- alws/schemas/build_schema.py
This change is needed for [front-end PR](https://github.com/AlmaLinux/albs-frontend/pull/209)
> Add ref to modules

- alws/utils/templates/errata_alma_page.j2
This depends on https://github.com/AlmaLinux/errata_index/pull/1
> ALBS-549: Updated errata page temlpate to use assets from errata_index

- alws/crud/build_node.py
- alws/utils/noarch.py
`IntegrityError` raises in case, if we try to process noarch packages in latest build task in line and when this build task have status `EXCLUDED`
> Fixed integrity error, added logs in build_done

- alws/crud/actions.py
- alws/crud/roles.py
- alws/crud/sign_task.py
- alws/release_planner.py
- scripts/manage_users.py
- Fixed permissions check on release update;
- Added ability for faster fixes of user permissions.
> Fixed RBAC for releases

- reference_data/platforms.yaml
Using standard repositories for c390x
> Update s390x arch

- alws/crud/build_node.py
Reverts AlmaLinux/albs-web-server#315
> Revert "ALBS-546: asio.src placed to mariadb module but should be in mariadb-devel"

- alws/build_planner.py
- alws/crud/build.py
- alws/schemas/build_schema.py
- alws/utils/modularity.py
BS only allows to ADD modules but not remove modules that come from modulemd.src.txt. Also BS automatically enable module we’re going to build and does not allow to disable it.
> ALBS-324 Enabled modules for module build should be fully configurable in UI

- reference_data/platform_flavors.yaml
We're going to enable this later
> Remove beta specific macros for now

- alws/build_planner.py
- alws/schemas/build_schema.py
- alws/utils/beholder_client.py
If beta flavor is enabled the system will attempt to get artifacts from related beta distribution to create partial update case.
> Added ability to read module artifacts from beta

- alws/middlewares/__init__.py
- alws/middlewares/not_found.py
- alws/middlewares/sign_task.py
Current we got non-useful message about error Dismiss and 500 error in a browser’s console
> ALBS-669 Add a meaningful message error when signing builds

- alws/crud/build.py
When searching for something on BS, the total page number is wrong
> ALBS-111 Fix wrong total pages number in search

- alws/crud/build.py
> INFO:     172.18.0.11:60472 - "GET /api/v1/build_node/get_task HTTP/1.1" 200 OK
> INFO:     172.18.0.11:60480 - "GET /api/v1/build_node/get_task HTTP/1.1" 200 OK
> INFO:     172.18.0.11:35544 - "GET /api/v1/build_node/get_task HTTP/1.1" 200 OK
> INFO:     172.18.0.14:44660 - "POST /api/v1/sign-tasks/get_sign_task/ HTTP/1.1" 200 OK
> INFO:     172.18.0.12:49838 - "GET /api/v1/platforms/ HTTP/1.0" 200 OK
> INFO:     172.18.0.12:49836 - "GET /api/v1/users/all_users HTTP/1.0" 200 OK
> INFO:     172.18.0.12:49848 - "GET /api/v1/users/all_users HTTP/1.0" 200 OK
> INFO:     172.18.0.12:49846 - "GET /api/v1/builds/?pageNumber=1 HTTP/1.0" 200 OK
> /code/./alws/crud/build.py:201: RuntimeWarning: coroutine 'AsyncSession.execute' was never awaited
>   return await db.execute(await …
> ALBS-942: Fix promise handling

- alws/build_planner.py
- alws/crud/build_node.py
- alws/crud/errata.py
- alws/crud/products.py
- alws/crud/sign_task.py
- alws/crud/test.py
- alws/dramatiq/products.py
- alws/release_planner.py
- alws/schemas/build_schema.py
- alws/scripts/git_cacher/git_cacher.py
- alws/utils/asyncio_utils.py
- alws/utils/multilib.py
- alws/utils/noarch.py
- scripts/packages_exporter.py
Reverts AlmaLinux/albs-web-server#396
> Revert "ALBS-920: Replaced base asyncio gather method"

- alws/dramatiq/tests.py
- docker-compose.yml
We need to create a new queue and container for processing test tasks.
> ALBS-971 Add new queue for test completion tasks

- alws/crud/sign_task.py
See for details: https://cloudlinux.atlassian.net/browse/ALBS-1019
> ALBS-1019: Fixed deduplication at get_available_sign_task()

- alws/alembic/versions/237d7e07633e_added_module_column_to_erratarecord.py
Note to myself - Check db migrations right after merging with upstream/master
> ALBS-952: Fixed alembic migration

- alws/crud/errata.py
Actually, we only write “Successfully released” to it, while I’d say we can add some useful information, such as:
- errata id
- architecture(s)
- is module
- pulp repositories
- packages
- timestamp
> ALBS-1013 Add more information to errata release logs

- alws/crud/test.py
- alws/dramatiq/build.py
- alws/dramatiq/tests.py
This commit fixes 2 issues:
1. Test tasks were not created if last build task was failed or excluded;
2. Test task completion workflow was improved to make sure all test tasks will receive corresponding "final" statuses even if unexpected issues occure.
> Ensure test tasks will be started and completed

- reference_data/platforms.yaml
Try to increate RLIMIT_NOFILE to fix issues with dotnet7.0 build on PPC64le
> Increase RLIMIT_NOFILE

- reference_data/platforms.yaml
This reverts commit f2727422ab7c29dd09fa84872dabfe8190b57c4a.
> Revert "Add kernel-rpm-macros to AlmaLinux-9 chroot"

- reference_data/platforms.yaml
> Update AlmaLinux 9 stable platform with module version and SB cert

- alws/auth/oauth/github.py
- alws/constants.py
- alws/dramatiq/build.py
- scripts/generate_token.py
- Simplified GitHub Oauth client setup since underlying library now has pretty much the same code as we do, so there's no point in subclassing;
- Take CANCELLED build task status into account when finalizing the build;
- Added script to generate long-living JWT tokens for service needs.
> Small fixes and code improvements

- requirements.txt
This should fix our problems with testing, see https://github.com/pydantic/pydantic/issues/5821
> Bump Pydantic from 1.10.7 to 1.10.8

- alws/middlewares/__init__.py
- alws/middlewares/builds.py
- alws/schemas/build_schema.py
- tests/fixtures/builds.py
- tests/mock_classes.py
- tests/test_api/test_builds.py
Solves https://github.com/AlmaLinux/build-system/issues/18
Here is an example of showing error to user:
> Add validation for `BuildTaskModuleRef`

- alws/auth/transport.py
Reverts AlmaLinux/albs-web-server#592
> Revert "Fix transport classes to work with latest fastapi-users library"

- scripts/bootstrap_repositories.py
> Added exception handling to bootstrap repositories script

- reference_data/platforms.yaml
This PR add Testing repo for 8 and 9.
> Add AlmaLinux Testing repo

- docker-compose.yml
- Mount requirements.txt
- Mount sources
- Update pip & reinstall all requirements on launch if a developer changed them before
> Mount sources instead copy them into a Docker image:

- alws/utils/templates/errata_alma_page.j2
While here, apply html formatter.
Resolves: https://github.com/AlmaLinux/build-system/issues/107
> errata: link each erratum to index page

- tests/fixtures/products.py
- tests/test_api/test_products.py
We should remove a product's team in tests because ALBS creates a new team per each new product
> - Fix GH CI

- .github/workflows/commit-message.yml
Fixes https://github.com/AlmaLinux/build-system/issues/96
> Set up a github action to checks that commit messages follow the commit guidelines

- alws/build_planner.py
- alws/crud/build_node.py
- alws/dramatiq/build.py
- alws/routers/build_node.py
- alws/schemas/build_schema.py
- alws/utils/noarch.py
Reverts AlmaLinux/albs-web-server#667
> Revert "AlmaLinux/build-system#87: ALBS can't build multiplatform builds beca…"

- alws/build_planner.py
- alws/crud/build_node.py
- alws/dramatiq/build.py
- alws/routers/build_node.py
- alws/schemas/build_schema.py
- alws/utils/noarch.py
Reverts AlmaLinux/albs-web-server#674
> Revert "Revert "AlmaLinux/build-system#87: ALBS can't build multiplatform builds beca…""

- .github/workflows/pytest.yml
- .github/workflows/syntax.yml
- README.md
- alws/crud/roles.py
Add test coverage information on the main page of albs-web-server repository
Fixes: AlmaLinux/build-system#141
> Add test coverage information on the main page of web-server repo

- docker-compose.yml
Fixes: https://github.com/AlmaLinux/build-system/issues/160
> Update path to dockerfile for tests_cacher VM

- scripts/packages_exporter.py
While here, include only recent 500 entries in RSS feed.
Resolves: https://github.com/AlmaLinux/build-system/issues/155
> Sort RSS feed by pubDate

- alws/crud/products.py
- alws/crud/sign_task.py
- alws/perms/roles.py
- alws/routers/products.py
* Fixes `sqlalchemy.exc.MissingGreenlet` errors
> Fixes AlmaLinux/build-system#157

- alws/routers/errata.py
Resolves: AlmaLinux/build-system#103
> Open Security Advisories & COPR list

- .github/workflows/pytest.yml
- .github/workflows/syntax.yml
Resolves: AlmaLinux/build-system#181
> Bump github actions dependencies

- docker-compose.yml
Resolves: https://github.com/AlmaLinux/build-system/issues/175
> make redis cache (git cache) persistent

- alws/auth/transport.py
- alws/auth/user_manager.py
- requirements.txt
Resolves: https://github.com/AlmaLinux/build-system/issues/187
> Update dependencies to mitigate security risks

- .github/workflows/migrations-check.yml
Resolves: https://github.com/AlmaLinux/build-system/issues/190
See [working example here](https://github.com/javihernandez/albs-web-server/actions/runs/7902734253/job/21569029136?pr=6)
> Update migration checks workflow to try merging if rebasing fails

- alws/routers/errata.py
Fixes: AlmaLinux/build-system#199
> Fix 401 when click to the Advisory info

- alws/crud/errata.py
- alws/routers/errata.py
- scripts/packages_exporter.py
Fixes: https://github.com/AlmaLinux/build-system/issues/195
> Ensure that OVAL data contains released records only

- alws/config.py
- alws/constants.py
- alws/crud/build.py
- alws/crud/build_node.py
- alws/crud/errata.py
- alws/dramatiq/build.py
- alws/release_planner.py
- alws/routers/errata.py
- alws/utils/github_integration_helper.py
- requirements.txt
Resolves: AlmaLinux/build-system#70
Resolves: https://github.com/AlmaLinux/build-system/issues/193
Resolves: https://github.com/AlmaLinux/build-system/issues/191
Resolves: https://github.com/AlmaLinux/build-system/issues/185
> Move issues to the correct statuses

- alws/crud/repository.py
Resolves: https://github.com/AlmaLinux/build-system/issues/184
This works fine for me but I'm checking if the same fix are needed in other place.
> Do not overwite columns with None when updating repository

- alws/utils/copr.py
Resolves: https://cloudlinux.atlassian.net/browse/ALBS-903
> Fix COPR repository URL to be arch- and distribution-agnostic

- alws/crud/build_node.py
- alws/crud/errata.py
- alws/dramatiq/build.py
- alws/release_planner.py
- alws/utils/github_integration_helper.py
Fixes AlmaLinux/build-system#237
> Fix GitHub integration

- alws/build_planner.py
- alws/crud/release.py
- alws/crud/sign_task.py
- alws/dramatiq/products.py
- alws/perms/actions.py
- alws/perms/roles.py
- alws/release_planner.py
- alws/routers/releases.py
- tests/fixtures/builds.py
- tests/fixtures/dramatiq.py
Fixes https://github.com/AlmaLinux/build-system/issues/133
- Select a proper repo for a package (by arch, type of package (debug or not) and platform ID) while getting/completing a sign task
- Exclude a repo with sign_key while selecting a product's repos
- It's added endpoint to delete only scheduled release plan (for test and following prod purposes)
- Select packages for only one platform while preparing a release plan
- Comments from linter black are fixed
- The tests are fixed
**This is rebased branch**
Original branch AlmaLinux/build-system-133
> ALBS can't release/add a multi-platform build to a product

- alws/build_planner.py
- alws/dramatiq/build.py
- alws/models.py
Fixes: https://github.com/AlmaLinux/build-system/issues/243
> Fix build tasks dependencies creation

- docker-compose.yml
- alts-celery
- alts-scheduler
- build_node
- sign_node
- tests_cacher
Resolves: AlmaLinux/build-system/issues/252
> Set up services in docker-compose.yml

- alws/crud/errata.py
- alws/release_planner.py
- alws/utils/github_integration_helper.py
- requirements.txt
Fixes: AlmaLinux/build-system#241
> Fix duplicates GitHub Issues

- alws/config.py
- alws/crud/build_node.py
- alws/database.py
- alws/utils/pulp_utils.py
- tests/fixtures/pulp.py
- tests/test_api/test_builds.py
- tests/test_api/test_releases.py
Fixes: https://github.com/AlmaLinux/build-system/issues/251
> Delete module in pulp if required when rebuilding failed tasks

- .github/workflows/migrations-check.yml
- .github/workflows/pytest.yml
- Dockerfile
- Dockerfile.git-cacher
- Dockerfile.gitea-listener
- Dockerfile.task-queue
- docker-compose.yml
Also service configurations in docker-compose.yml were refactored.
> Use the almalinux/9-base image for the containers

- reference_data/centos6.yml
- reference_data/centos7.yml
We need this platform to build ELevate packages for CentOS 6
> Add CentOS 6 build platform

- alws/routers/uploads.py
- alws/utils/modularity.py
- alws/utils/pulp_client.py
- alws/utils/uploader.py
- scripts/upload_repository_metadata.py
Fixes: https://github.com/AlmaLinux/build-system/issues/192
> Fix manual metadata upload

- alws/crud/errata.py
- alws/routers/errata.py
Resolves: https://github.com/AlmaLinux/build-system/issues/206
> Take into account platform_id in updateinfo endpoint

- alws/crud/errata.py
Fixes https://github.com/AlmaLinux/build-system/issues/271
> Update GPG Key ID for AL8 Oval

- alws/crud/errata.py
- alws/utils/oval_add_al8_gpg_keys.py
- alws/utils/oval_add_gpg_keys.py
Fixes https://github.com/AlmaLinux/build-system/issues/205
> Adds support for multiple GPG keys

- alws/crud/products.py
- alws/routers/uploads.py
- alws/utils/uploader.py
- tests/conftest.py
- tests/fixtures/products.py
- tests/fixtures/repositories.py
- tests/fixtures/uploader.py
- tests/test_api/test_uploads.py
Resolves: https://cloudlinux.atlassian.net/browse/ALBS-1211
> Check permissions for uploading repository metadata

- Dockerfile
Fixes https://github.com/AlmaLinux/build-system/issues/285
> Added gcc and python-dev to Dockerfile

- requirements.txt
See: https://github.com/google/osv.dev/issues/2281
> Bump errata2osv from 0.0.3 to 0.0.4

- alws/crud/errata.py
Resolves: https://github.com/AlmaLinux/build-system/issues/250
Frontend: https://github.com/AlmaLinux/albs-frontend/pull/477
> Separated packages list in failed errata release

- alws/utils/pulp_utils.py
Fixes: https://github.com/AlmaLinux/build-system/issues/305
> Disable expire_on_commit in some interactions with pulp db

- alws/perms/roles.py
Fixes: https://github.com/AlmaLinux/build-system/issues/315
> Make Role's actions attribute a List instead of an Iterable

- alws/release_planner.py
- alws/utils/noarch.py
Fix issue with noarch in 'src' task
Fix issue with empty errata pkgs in release commit
> Fix production issues

- alws/crud/products.py
- alws/crud/teams.py
- alws/routers/teams.py
Resolves: https://github.com/AlmaLinux/build-system/issues/295
* Anyone can now create teams/products, fixed 404 error during creation
* Team router dependency switched from super user to get_current_user
* can_perform checks added to endpoints, updated routers to pass user
> Add RBAC to teams API : 295

- alws/crud/user.py
Fixes: https://github.com/AlmaLinux/build-system/issues/320
> Remove unnecessary import

- alws/app.py
- alws/routers/__init__.py
- alws/routers/package_info.py
- alws/schemas/package_info_shema.py
- alws/utils/limiter.py
- requirements.txt
- tests/conftest.py
- tests/fixtures/limiter.py
- tests/fixtures/pulp.py
- tests/test_api/test_package_info.py
- Created `/package_info` endpoint
- Added rate limiting to the endpoint
Resolves: https://cloudlinux.atlassian.net/browse/ALBS-1221
> Provide the ability to use the "pulp/api"

- alws/constants.py
- alws/release_planner.py
Resolves: AlmaLinux/build-system#328
> Fix packages layout in the release plans

- alws/crud/test.py
- tests/test_test_scheduler/test_test_task_scheduler.py
Resolves: AlmaLinux/build-system#326
> Returning repos used in a build to ALTS

- reference_data/platform_flavors.yaml
Resolves: AlmaLinux/build-system#330
> - Pungi10 as build-flavor

- alws/crud/products.py
- alws/dependencies.py
- alws/utils/copr.py
- alws/utils/exporter.py
- alws/utils/pulp_client.py
- scripts/add_export_paths_to_product_repos.py
- scripts/exporters/base_exporter.py
- scripts/exporters/packages_exporter.py
- scripts/exporters/products_exporter.py
- tests/test_scripts/test_packages_exporter.py
Resolves: AlmaLinux/build-system#354
> Add products exporter

- alws/crud/products.py
- alws/routers/products.py
- tests/fixtures/products.py
- tests/test_api/test_products.py
Resolves: AlmaLinux/build-system#358
> Add ability to add new platforms to the product

- reference_data/platform_flavors.yaml
- reference_data/platforms.yaml
Please don't merge it until the request
> Update remote_url and export_path for AlmaLinux-Kitten-10

- tests/fixtures/pulp.py
Create new event loop for each test
Resolves: AlmaLinux/build-system#367
> Fix event loop error in tests

- alws/crud/products.py
- alws/routers/products.py
- Add access control
- Black formatting
Resolves: AlmaLinux/build-system#359
> Add access control to `products/{id}/add_platforms`

- reference_data/platforms.yaml
- Add raspberrypi repo for AL10
- Add raspberrypi repo for ALK10
> - Remove beta repos from AL10 platform

- tests/fixtures/dramatiq.py
Resolves: AlmaLinux/build-system#392
> Test alws.dramatiq.builds._build_done()

- alws/crud/errata.py
Fixes: https://github.com/AlmaLinux/build-system/issues/400
> Fix sorting when listing errata records

- alws/alembic/versions/63bc4e0b699f_add_many_to_many_relationship_between_.py
- alws/crud/sign_key.py
- alws/models.py
- alws/routers/sign_key.py
- alws/schemas/sign_schema.py
- tests/fixtures/sign_keys.py
- tests/test_api/test_sign_keys.py
- alembic migration
- change in models
- added a test for one platform with 2 keys
Fixes: AlmaLinux/build-system#370
> Add many-to-many to plaforms-sign_keys (AlmaLinux/build-system#370)

- alws/crud/build_node.py
- alws/schemas/build_node_schema.py
Implement mechanism for excluding projects on a node
- Change build_node/get_task Request model
- Look up available tasks based on excluded_packages
- black formatting
Resolves:  AlmaLinux/build-system#365
> Exclude builds from node

- alws/crud/build_node.py
Resolves: https://github.com/AlmaLinux/build-system/issues/402
> Stop mapping errata packages at build_done

- .github/workflows/preflight.yml
- .github/workflows/run-tests.yml
Fixes: https://github.com/AlmaLinux/build-system/issues/429
> Use OVAL_PROCESSOR_SECRET to clone oval-processor in actions

- alws/build_planner.py
Fixes: AlmaLinux/build-system#404
> Fix Individual mock options are not taken into account

- alws/crud/errata.py
- alws/schemas/errata_schema.py
Only look for packages in ALBS and not in production
Fixes: https://github.com/AlmaLinux/build-system/issues/378
Fixes: https://github.com/AlmaLinux/build-system/issues/415
> Alternative errata package processing for erratas created by us

- alws/release_planner.py
- alws/routers/build_node.py
* Adjust platform dnf_common_opts with data from platform flavours
* Fix regex for getting pretty product repository names
> Backport production changes

- alws/utils/modularity.py
Fixes: https://github.com/AlmaLinux/build-system/issues/447
> Allow tilde symbol in RpmArtifact's version

- alws/crud/build.py
- alws/routers/builds.py
- alws/schemas/build_schema.py
- alws/scripts/git_cacher/git_cacher.py
- alws/utils/modularity.py
Resolves: https://github.com/AlmaLinux/build-system/issues/438
> Update the method to retrieve the list of modified packages

- alws/release_planner.py
Fixes: AlmaLinux/build-system#459
> Fix adding repositories to release plan

- reference_data/platform_flavors.yaml
- Use one product for alt arch EPEL
> - Update EPEL for 10

- alws/dramatiq/__init__.py
- alws/dramatiq/build.py
- alws/routers/build_node.py
- docker-compose.yml
Resolves: https://github.com/AlmaLinux/build-system/issues/497
> Move processing source packages into a separate dramatiq queue

- reference_data/platform_flavors.yaml
Add flavor to add --nobest to dnf.
Useful for bootstrap.
> Add nobest flavor

- scripts/backup_beta_repos.py
Resolves: https://github.com/AlmaLinux/build-system/issues/507
> Take beta repos to backup from commandline arguments
