AlmaLinux/albs-web-server

- alws/config.py
- alws/releases.py
We may have a situation when the system that is predicting packages is
unavailable and we need to just create a release plan on our own. This
commit brings support for such case.
> ALBS-20: Added flag whether "oracle" is enabled.

- alws/crud.py
- alws/utils/noarch.py
- Added new module `alws/utils/noarch.py`
- Implemented functions for saving/replacing noarch packages between different architectures
Tested on packages `grub2` and `mingw-glib2`
> ALBS-38: Added ability to save/replace noarch packages between different architectures

- alws/crud.py
- alws/errors.py
- alws/routers/build_node.py
Fix the case when build node tries to report task as built when it's
already marked so. Send 409 HTTP code in such case.
> ALBS-85: Send a special code when build is already done

- alws/scripts/albs-gitea-listener/Dockerfile
Because:
```
Traceback (most recent call last):
File "gitea_listener.py", line 23, in <module>
from git_cacher import load_redis_cache, save_redis_cache
File "/code/git_cacher.py", line 9, in <module>
from alws.utils.gitea import GiteaClient
ModuleNotFoundError: No module named 'alws'
```
> ALBS-71: Implement single deploy mechanism of new BS

- alws/build_planner.py
- alws/utils/parsing.py
ALBS-28. Dist macro should be automatically taken from a git tag.
But if 'definitions.dist' is set this value will be used  instead of any parsed
> ALBS-28. Dist macro should be automatically taken from a git tag.

- reference_data/platforms.yaml
ResilientStorage doesn't exist for aarch64, so we have to delete that repo
> Remove ResilientStorage for aarch64

- alws/build_planner.py
- alws/crud/build_node.py
- alws/routers/build_node.py
- alws/schemas/build_schema.py
- alws/utils/gitea.py
- alws/utils/modularity.py
- alws/utils/pulp_client.py
This commit allows building devel-modules alongside with default ones.
Whenever you're building module now, we'll check for it's devel version and build it together, if present
There are significant api changes in `alws/utils/modularity.py`:
* `class ModuleWrapper` now contains only one stream, without module/index (Initial implementation was backported from old bs and required changes to build multiple modules in one modules.yaml). You can't make new ModuleWrapper from string anymore if template has more than one module in it.
* `class IndexWrapper` (new class) is now should be used if you don't know for sure, how many module templates inside modules.yaml, or want to build multiple modules. All places in code, where we can find multiple modules at once, now using `IndexWrapper` instead …
> Devel modules can be built

- alws/build_planner.py
- alws/crud/build.py
- alws/utils/modularity.py
- alws/utils/pulp_client.py
This commit adds ability to set empty streams for build time and runtime
modules dependencies in modules.yaml file to correct ones from mock
options.
> ALBS-110: Fix empty streams based on mock options

- alws/crud/repo_exporter.py
- alws/routers/repositories.py
- alws/utils/pulp_client.py
- alws/utils/repository.py
- docker-compose.yml
- requirements.txt
Added a couple of libs. Also changed some volumes (web-server have to store repodata near exported repos by pulp). So the docker images albs-web-server_web_server_1 should be rebuilt.
For pulp config pulp/setting/setting.py we should use ALLOWED_EXPORT_PATHS=['/srv/exports'] line to allow exporting
> Albs 73 with repodata exporting

- alws/constants.py
- alws/crud/build_node.py
- alws/crud/distribution.py
- alws/crud/sign_task.py
- alws/crud/test.py
- alws/dramatiq/build.py
- alws/dramatiq/sign_task.py
- alws/errors.py
- alws/models.py
- alws/utils/ids.py
- alws/utils/modularity.py
- alws/utils/pulp_client.py
- alws/utils/uploader.py
This commit brings several things to make `build_done` endpoint more reliable:
1. Separate exceptions for different things: help react on a particular error;
2. Increased timeout for the `build_done` dramatiq actor;
3. Reworked build artifacts processing: now packages are added to the repository only when all of them were converted from artifacts to actual RPM packages;
4. Improved logs handling: logs are processed similarly to packages, but now they are first in line and committed separately from packages;
5. Modules errors handling: both parsing initial data and adding new artifacts.
> Fixed build_done method. Improved reliability of task finish

- alws/utils/pulp_client.py
This is sequence in which pulp retain old repo versions / creates new one:
```
pulpcore.app.models.repository:INFO: Deleting repository version <Repository: AlmaLinux-9-i686-19-br; Version: 7> due to version retention limit.
pulp_rpm.app.tasks.publishing:INFO: Publishing: repository=AlmaLinux-9-i686-19-br, version=8
pulp_rpm.app.tasks.publishing:INFO: Publication: f87e0429-aef3-4cb7-8c95-ab6bdaa19e34 created
```
As you can see, if you have only 1 version in your repository, there is a point in time, in which there is 0 publications for given repository, which cause 404 errors on our builds pipeline
> Fix 404 on repodata/packages while build is in progress

- reference_data/platforms.yaml
- reference_data/production_platforms.yaml
- Update chroots to use almalinux-release
- Added modules version 8.6 to AlmaLinux 8
- Use c9/a9 branch prefixes for AlmaLinux 9
> Update AlmaLinux platforms

- reference_data/platforms.yaml
- Remove -beta from git_tag_prefix for AlmaLinux9
- Update modified packages url for AlmaLinux8 and AlmaLinux9
> modified_packages was split to a8 and a9 branches, we should update links

- alws/utils/pulp_client.py
This change is actually coming from @vasilykleschov. We applied this change while setting up my local dev environment
> ALBS-441: Updated Pulp's RPM repo sync to Pulp API v3

- alws/build_planner.py
- alws/schemas/build_schema.py
Now the per-project mock options are taken into account
> ALBS-388: Ensure that per-project mock_options are taken into account

- reference_data/platforms.yaml
Hello, I mistake, when I was creating a beta repository for s390x, so we need to change the link to this repository
> Use correct link to beta repository for s390x

- alws/release_planner.py
We should update beholder info for packages with "weak" arches, because it breaks our approach: `ReferencePlatform -> AlmaLinux`
Right now it works like this:
- we get sorted beholder responses by priority (i.e.` [AlmaLinux, ReferencePlatform]`)
- if we found package info for weak arch in AlmaLinux, in next beholder response we do not override it
> Fixed packages searching for weak arches

- reference_data/platform_flavors.yaml
- reference_data/platforms.yaml
- Add AlmaLinux-9-beta flavor for 9.1 Beta
- Update AlmaLinux-8-beta flavor for 8.7 Beta
- Remove beta repos from AlmaLinux 9 stable platform
- Use EPEL flavor name instead of Epel
> Update beta flavors and remove beta repos from AlmaLinux 9 stable

- alws/crud/build_node.py
- We should add a source RPM into a non-devel module if a source RPM produced
at least one RPM. Otherwise, we should add that source RPM into a devel module.
> ALBS-546: asio.src placed to mariadb module but should be in mariadb-devel

- alws/utils/errata.py
- alws/utils/pulp_client.py
- scripts/packages_exporter.py
- Fixed 400 error when starting the exporter;
- Re-using existing exporters instead of deleting/creating them from scratch;
- Cache repodata after re-generation to production-like mode;
- Cache packages checksums via `createrepo_c`;
- Allowed for parallel export of AlmaLinux 8 and 9;
Repodata and checksums caching as well as re-use of existing exporters allowed to reduce export time significantly.
Previously export took 1-1.5 hours depending on Pulp host load. Now it takes 15-20 minutes.
> Pulp exporter improvements

- alws/build_planner.py
- alws/crud/build_node.py
- alws/utils/beholder_client.py
Instead of working with artifacts that we get from the preview `modules.yaml` we call beholder for each build task (basically each architecture) and add artifacts from there to the empty artifacts list. This allows us to avoid errors with multiple artifacts being placed in the same module which happens for example in javapackages-tools module.
> Reworked logic of populating module index

- alws/build_planner.py
- alws/utils/modularity.py
When we build module we build 2 modules actually:
- NAME
- NAME-devel
devel module must have requirement on main module.
So for example if we build subversion-devel:1.10 module it should require subversion:1.10
> ALBS-755 FIx devel module doesn't have requirement on main module

- reference_data/platforms.yaml
Without it we can't be sure that building with latest dependencies
> Enable best dnf option for AlmaLinux 9

- alws/routers/build_node.py
- reference_data/platforms.yaml
Mock option in build flavor is not added to build config
It should be work like it works in secure boot builds
> ALBS-787 Fix mock option in build flavor is not added to build config

- alws/utils/pulp_client.py
Also, updated list_updateinfo_records method so it can be called without specifying the repository
As of context, I made these changes for a script that I'm working on to check for some errors in errata/modules.
> ALBS-950: Added method to get modules in pulp_client

- README.md
The code snippet for setting up albs-web-server using docker-compose creates the settings file in an incorrect location, causing an error when resetting the admin password.
The problem is that the volumes directory should not be created in the directory where the docker-compose.yml file is located, but rather the parent directory.
This commit fixes the path in the code snippet so that settings.py is created in the correct location.
This is a very trivial PR, but it took me a bit to understand why the error was shown, so I figured it's worth submitting this. :)
> Fix settings path in setup code snippet

- .github/workflows/pytest.yml
- alws/build_planner.py
- alws/crud/build_node.py
- alws/crud/roles.py
- alws/crud/test.py
- alws/dramatiq/__init__.py
- alws/dramatiq/build.py
- alws/models.py
- alws/routers/build_node.py
- tests/fixtures/dramatiq.py
- tests/fixtures/pulp.py
Currently we produce a build log repository for each build task. To make matters worse we produce test log repositories in the same fashion. All this puts a lot of pressure on the Pulp while creating build/making it finished. To avoid these problems we migrate to the flow when we have only 1 build log repository per build and one test log repository.
> Use 1 log repository per build

- alws/crud/errata.py
Some erratas in x86_64 repo were missing some (if not all of them) x86_64 packages.
> ALBS-1018: Ensure x86_64 updateinfo has both x86_64 and i686 packages

- alws/schemas/platform_schema.py
- scripts/bootstrap_permissions.py
**Summary: every database deployment script was outdated.**
- The initial problem happened because the deployment script didn’t set the 'product.is_community' flag correctly;
- The second problem happened because pulp’s gunicorn query parameter length limit was too small (4096);
- The last problem happened because PlatformCreate model was outdated in bootstrap_repositories.py script.
See for details: https://cloudlinux.atlassian.net/browse/ALBS-1024
> ALBS-1024: Fixed bootstrap scripts

- .github/workflows/pytest.yml
We have tested this, see https://github.com/javihernandez/albs-web-server/pull/4
> Use pull_request_target to allow commenting on PRs coming from forks

- reference_data/platform_flavors.yaml
Before: 
https://cloudlinux.atlassian.net/browse/ALBS-1034 
After:
Secure boot OFF:
Secure boot ON:
> ALBS-1034: Fix secure boot macro in flavours

- reference_data/platforms.yaml
kernel-rpm-macros package causes `kmod-kvdo` package to Provide `ksym(*) = *` entries which is not right.
The only reason to add this package to setup_chroot_cmd was modules signing but it's not actually required for that.
> Undo ALBS-278: Added kernel-rpm-macros package to setup_chroot_cmd

- reference_data/platforms.yaml
The way how `nspawn_args` is implemented now in ALBS rewrites `--capability=cap_ipc_lock` argument which is used by default in mock.
This PR brings it back.
> Add missing --capability=cap_ipc_lock to nspawn_args

- alws/build_planner.py
```
[2023-04-18 09:57:53,410] [PID 29] [MainThread] [dramatiq.WorkerProcess(8)] [INFO] Worker process is ready for action.
[2023-04-18 09:57:53,332] [PID 30] [MainThread] [dramatiq.WorkerProcess(9)] [INFO] Worker process is ready for action.
[2023-04-18 09:57:53,170] [PID 31] [MainThread] [dramatiq.WorkerProcess(10)] [INFO] Worker process is ready for action.
[2023-04-18 09:57:53,419] [PID 32] [MainThread] [dramatiq.WorkerProcess(11)] [INFO] Worker process is ready for action.
[2023-04-18 09:57:53,426] [PID 640] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
[2023-04-18 18:22:56,886] [PID 23] [Thread-40] [dramatiq.worker.WorkerThread] [ERROR] Failed to process message start_build(1, {'platforms': …
```
> ALBS-1080: Fix logs repository creation

- alws/release_planner.py
This change fixes the issue where we can't release builds to old-style products that contain camel case platform names.
> ALBS-1088: Ignore case when checking the platform of a product repo

- requirements.txt
Reverts AlmaLinux/albs-web-server#587
> Revert "Bump fastapi-users[all] from 10.4.1 to 12.1.0"

- alws/release_planner.py
When making a community package release, duplicate packages are not filtered, causing noarch packages to appear multiple times (once per build architecture) in the list.
This commit modifies CommunityReleasePlanner.get_release_plan() so that it filters duplicate packages by their full name. This is the same approach as in the AlmaLinuxReleasePlanner class.
> alws/release_planner: Filter duplicate packages in community releases

- Dockerfile
- Dockerfile.git-cacher
- Dockerfile.gitea-listener
- Dockerfile.task-queue
- docker-compose.yml
- Copying the code into the images is removed
- Pull the already built image from quay.io
> AlmaLinux/build-system#57: Mount the sources to a container (albs-web-server, albs-sign-node) instead store them into a container

- alws/utils/errata.py
- scripts/albs-1147.py
This pull request includes a script to fix errata branding issues across Pulp's update records and AlmaLinux's errata records.
1. **Debranding Functionality**: The script introduces a debranding function that replaces occurrences of specific patterns such as 'RHEL' with 'AlmaLinux' in titles and descriptions.
2. **Log Differences**: Added logging capabilities to detail the differences before and after the debranding process. This allows for easier tracking and verification of changes.
3. **Database Updates**: The changes are implemented across both Pulp's `rpm_updaterecord` table and AlmaLinux's `errata_records` table. The script selectively searches for records with specific keywords, ignoring some pre-defined parts, and updates them accordingly.
4. **Write Control**: The script supports …
> Fix Errata Branding Issues in Pulp and AlmaLinux Databases

- alws/utils/templates/errata_alma_page.j2
Found this I'm working on: https://github.com/AlmaLinux/build-system/issues/39
See also: https://www.w3.org/International/questions/qa-html-encoding-declarations.en
> Fix unpaired double quotation in errata html template

- alws/utils/errata.py
- alws/utils/templates/errata_alma_page.j2
* Add ability to change sort order
* Display package checksums in errata page that was unintentionally not displayed
* Show updated packages as compact table
Merge https://github.com/AlmaLinux/errata_index/pull/4 together.
> Implement packages sorting in errata page

- .github/workflows/syntax.yml
- alws/crud/build_node.py
- alws/utils/multilib.py
- The "multilib" call to repo-beholder is fixed
- The artifacts from other arch than `i686` don't contain sRPM. So, we should extract name of sRPM from its URL
> AlmaLinux/build-system#113: Fix multilib in builds

- requirements.txt
- scripts/packages_exporter.py
Outputs `errata.rss` under the following directory:
```
./exports/errata
├── AlmaLinux-9
│   ├── errata.full.json
│   ├── errata.json
│   ├── errata.rss
│   └── html
│       ├── ALSA-2022-4940.html
│       ├── ALSA-2022-5099.html
│       ├── ALSA-2022-5242.html
│       ├── ALSA-2022-5244.html
│       ├── ALSA-2022-5249.html
```
So final URL will be 
* https://errata.almalinux.org/9/errata.rss
* https://errata.almalinux.org/8/errata.rss 
This is a sample of generated RSS:
* [errata_20231004_rss.txt](https://github.com/AlmaLinux/albs-web-server/files/12800138/errata_20231004_rss.txt)
* https://w.vmeta.jp/temp/errata.rss
> Add RSS feed generation to packages_exporter

- docker-compose.yml
Current configuration mounts sources one level deeper than expected:
```
/sign-node/sign_node/sign_node/__init__.py
```
Correct mount path should be:
```
/sign-node/sign_node/__init__.py
```
> docker-compose: correct volume path for sign_node

- docker-compose.yml
- mosquitto-no-auth.conf
Added config file for mosquitto service so it will listnen on all inerfaces.
Without this setting git-listener cant connect to it Related to https://github.com/AlmaLinux/build-system/issues/132
> MQTT now listens on all interfaces

- docker-compose.yml
1. node_modules dir now mounts as named volume
2. changed bind mount for code since container now runs as albs user
Related to
- https://github.com/AlmaLinux/build-system/issues/131
- https://github.com/AlmaLinux/albs-frontend/pull/392
> Required changes after adding albs user for albs_frontend container

- alws/crud/test.py
After a "Restart build tests" action only affected tests should restart
Resolves: AlmaLinux/build-system#169
> ALBS-1061: Fix "Restart build tests" functionality

- alws/scripts/git_cacher/git_cacher.py
- alws/utils/gitea.py
Resolves: https://github.com/AlmaLinux/build-system/issues/183
Now it retries 5 times at maximum when errors occurred.
```
2024-02-09 08:57:25,080 [gitea-cacher:DEBUG] - Attempt to request [#1/5] https://git.almalinux.org/api/v1/orgs/rpms/repos, with params: {'limit': 50, 'page': 14}
2024-02-09 08:57:27,214 [gitea-cacher:DEBUG] - Attempt to request [#1/5] https://git.almalinux.org/api/v1/orgs/rpms/repos, with params: {'limit': 50, 'page': 15}
2024-02-09 08:58:27,599 [gitea-cacher:ERROR] - Error during making request: Server disconnected, https://git.almalinux.org/api/v1/orgs/rpms/repos, {'limit': 50, 'page': 15}
2024-02-09 08:58:27,599 [gitea-cacher:DEBUG] - Retrying attempt [#1/5] in 2 seconds: https://git.almalinux.org/api/v1/orgs/rpms/repos, with params: {'limit': 50, 'page': 15} …
```
> Add retry to git-cacher for robustness

- alws/database.py
- alws/models.py
- alws/pulp_models.py
- requirements.txt
Resolves: https://github.com/AlmaLinux/build-system/issues/203
What has been done:
- Configured `fastapi-users-db-sqlalchemy` and `SQLAlchemy` to the latest versions (6.0.1 and 2.0.27 respectively) in `requirements.txt`
- Added `DeclarativeBase` and `MetaData` (for `Base`) in `database.py` to replace `declarative_base()` for `Base` and `PulpBase`
- AsyncAttrs
- [Replaced](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#step-two-replace-declarative-use-of-schema-column-with-orm-mapped-column) declarative use of `Column` with `mapped_column()` in `models.py` and `pulp_models.py`
- Type hints for tables in `models.py` and `pulp_models.py`
> Migrate Sqlalcehmy to the v2

- scripts/bootstrap_permissions.py
Fixes: https://github.com/AlmaLinux/build-system/issues/229
> Bootstrap only system user, almalinux team and product

- reference_data/platform_flavors.yaml
This PR does the following:
1. Switch CS9 flavor to use koji repos directly: https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/
2. Fix typo in CS9 flavor name
3. Add CS10 flavor with koji repos: https://kojihub.stream.centos.org/kojifiles/repos/c10s-build/latest/
> Switch CS9 flavor to use koji repos directly and add CS10 flavor

- alws/models.py
- alws/pulp_models.py
Resolves: https://github.com/AlmaLinux/build-system/issues/203
Typehints. Adding Lists for Mapped in models.py and pulp_models.py
> List[CoreRepositoryContent]

- alws/release_planner.py
Fixes: https://github.com/AlmaLinux/build-system/issues/256
> Fix release plan for modular builds

- docker-compose.yml
There's no need now to use the `frontend_node_modules` volume and run `npm install` before any other `npm` command.
Resolves: AlmaLinux/build-system/issues/223
> Use the frontend image with preinstalled node_modules

- alws/crud/errata.py
- alws/routers/errata.py
Resolves: https://github.com/AlmaLinux/build-system/issues/213
> Added platform check

- pyproject.toml
That is the Black's default value.
See https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length
> Set Pylint's and Black's line length to 88 chars

- alws/utils/oval_add_al8_gpg_keys.py
Fix ImportError in tests for almalinux package
- Removed offending type annotations
- Enclosed `from almalinux import` in `try...except` block
Fixes: AlmaLinux/build-system#282
> Fix ImportError in tests for almalinux package

- alws/config.py
- alws/constants.py
- alws/crud/build_node.py
- alws/crud/errata.py
- alws/utils/github_integration_helper.py
- requirements.txt
Resolves: https://github.com/AlmaLinux/build-system/issues/239
Resolves: https://github.com/AlmaLinux/build-system/issues/253
> Add comments for gh issues

- alws/crud/errata.py
If the first match in the affected regex search is the devel module, we fail when trying to map errata packages later.
Fixes: https://github.com/AlmaLinux/build-system/issues/304
> Ensure we get the non-devel module from OVAL data

- alws/crud/errata.py
- alws/routers/errata.py
- alws/schemas/errata_schema.py
- tests/test_api/test_errata.py
- Added platfrom_id in response
- Enabled optional platform_id parameter for filtering errata records
- Added tests for /errata/all/ endpoint
Resolves: AlmaLinux/build-system#207
> Add platform_id in /errata/all/ endpoint

- alws/crud/test.py
The issue with linked builds is that we didn't ask for linked builds' build repositories, thus when we tried process the build with linked builds we would fail each time.
> Fix MissingGreenlet in getting new test tasks

- reference_data/platform_flavors.yaml
Currently ALBS has issues with accessing https://download.fedoraproject.org so switched to another address.
> Fix EPEL URL

- alws/crud/repository.py
- alws/routers/sign_key.py
- alws/schemas/repository_schema.py
- alws/schemas/sign_schema.py
- scripts/bootstrap_repositories.py
- tests/test_api/test_platforms.py
Provisioning data missing from albs-deploy
- writing owner_id to platforms, repositories and sign keys
- writing platform_id to repositories
- added test for platforms/{id}/add-repositories/ endpoint
Resolves: AlmaLinux/build-system#235
> Provisioning data missing from albs-deploy

- alws/build_planner.py
- alws/crud/build_node.py
- alws/crud/test.py
- alws/routers/build_node.py
Resolves: AlmaLinux/build-system#212
> Change build order

- alws/config.py
- alws/utils/github_integration_helper.py
Build URL was created after the usage in "create_github_issue" function
> Fix UnboundLocalError in errata endpoint

- docker-compose.yml
albs-deploy uses `-p albs` with docker compose so the project name is set to "albs" and the default network name is "albs_default", which is different from the current network name.
Use `$COMPOSE_PROJECT_NAME` to reference this dynamic project name.
Resolves: https://github.com/AlmaLinux/build-system/issues/317
> Use COMPOSE_PROJECT_NAME as the network name

- alws/crud/repository.py
- alws/schemas/remote_schema.py
- alws/utils/gitea.py
- alws/utils/github.py
- alws/utils/pulp_client.py
- scripts/bootstrap_repositories.py
Pulp does not respect environment variables like http_proxy for proxy
config, so it needs to be set directly.
This PR exposes three of the proxy related parameters as environment variables.
https://pulpproject.org/pulp_rpm/restapi/#tag/Remotes:-Rpm/operation/remotes_rpm_rpm_create
- PULP_PROXY_URL
- PULP_PROXY_USERNAME
- PULP_PROXY_PASSWORD
Also set trust_env=True to gitea session. aiohttp does not read proxy environment variables without this option.
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.trust_env
Resolves: https://github.com/AlmaLinux/build-system/issues/312
> Expose proxy config for pulp

- alws/crud/teams.py
- alws/crud/user.py
Resolves: https://github.com/AlmaLinux/build-system/issues/37
* Owner cannot be removed from team
* Owner's roles can never be changed
> Custom Product Access Management : 37

- reference_data/platforms.yaml
Resolves: https://github.com/AlmaLinux/build-system/issues/324
> Add 'rpmautospec_enable' flag to AlmaLinux 10 platform

- alws/routers/products.py
- scripts/generate_token.py
Resolves: https://github.com/AlmaLinux/build-system/issues/288
Done alongside: https://github.com/AlmaLinux/albs-sign-node/pull/114
• Uncommented sign task creation in create_product endpoint
• Tested and verified that sign keys are working correctly
> Ensure Product Sign Keys are Working Correctly : 288

- alws/crud/errata.py
- alws/dramatiq/__init__.py
- alws/dramatiq/errata.py
- alws/routers/errata.py
Resolves: https://github.com/AlmaLinux/build-system/issues/308
Frontend: https://github.com/AlmaLinux/albs-frontend/pull/504 (**there is a need to discuss the frontend part**)
```
[2024-08-02 14:31:33,515] [PID 36] [Thread-5] [root] [INFO] Packages for records ['4'] have been matched if their date is later than 2024-07-27 16:29:00
2024-08-02 14:35:20 [info     ] engine startup                 engine=Engine(postgresql+psycopg2://postgres:***@pulp/pulp) engine_key=pulp
2024-08-02 14:35:20 [info     ] engine startup                 engine=Engine(postgresql+psycopg2://postgres:***@db/db) engine_key=default
2024-08-02 14:35:20 [info     ] engine startup                 async_engine=<sqlalchemy.ext.asyncio.engine.AsyncEngine object at 0x7faf86bcce00> engine_key=async
2024-08-02 14:35:20 [info …
```
> Create endpoint to reset package mappings of unreleased erratas

- alws/schemas/build_schema.py
Resolves: https://github.com/AlmaLinux/build-system/issues/331
> Add riscv64 architecture into supported ones for build tasks

- reference_data/platform_flavors.yaml
- reference_data/platforms.yaml
- Add riscv64 architecture for AlmaLinux 10 and AlmaLinux Kitten 10
- Add AlmaLinux-10-beta-riscv64 flavor
- Add Fedora-40-riscv64 flavor to bootstrap riscv64
> Add RISC-V arch for AL10

- alws/crud/products.py
- alws/routers/products.py
- tests/test_api/test_products.py
This commit resolves the following problem during product creation:
```
web_server-1  | Traceback (most recent call last):
web_server-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
web_server-1  |     result = await app(  # type: ignore[func-returns-value]
web_server-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
web_server-1  |     return await self.app(scope, receive, send)
web_server-1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
web_server-1  |     await super().__call__(scope, receive, send)
web_server-1  |   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/starlette.py", line …
```
> Fix product creation

- alws/models.py
- tests/fixtures/products.py
This commit resolves the following problem during product deletion:
```
(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table \"products\" violates foreign key constraint \"gen_key_tasks_product_id_fkey\" on table \"gen_key_tasks\"\nDETAIL:  Key (id)=(2) is still referenced from table \"gen_key_tasks\".\n[SQL: DELETE FROM products WHERE products.id = $1::INTEGER]\n[parameters: (2,)]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)
```
> Fix product deletion

- reference_data/platform_flavors.yaml
- reference_data/platforms.yaml
- Add a flavor that contains patched libsolv for x86_64_v2
> - Remove the libsolv build from platfrom repositories

- reference_data/platform_flavors.yaml
This is to fix the:
```
Errors during downloading metadata for repository 'epel':
- Status code: 404 for https://d2lzkl7pfhq30w.cloudfront.net/pub/epel/10/Everything/x86_64/repodata/repomd.xml (IP: 2600:9000:24d6:b400:f:49cb:b400:21)
Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
> Set EPEL-10 flavor repositories' names to 'epel-10'

- .github/workflows/preflight.yml
- .github/workflows/run-tests.yml
- alws/config.py
- tests/README.md
- tests/fixtures/sign_keys.py
- tests/prepare_gpg_key.sh
- tests/test-vars.env
- tests/test_scripts/test_packages_exporter.py
- Enabling test integration between packages_exporter and sign_file
- Setting up albs-sign-file in preflight workflow
- Provisioning testing sign key in the workflow
Resolves: AlmaLinux/build-system#204
> Test integration between packages_exporter and albs-sign-file

- alws/crud/errata.py
- alws/dramatiq/errata.py
- alws/routers/errata.py
- Adding force parameter to bulk releases errata
- Setting IN_PROGRESS status in router
- black formatting
Resolves: AlmaLinux/build-system#325
> Preparing errata bulk releases for UI

- alws/crud/errata.py
- alws/dramatiq/__init__.py
- alws/dramatiq/errata.py
- alws/routers/errata.py
- alws/schemas/errata_schema.py
- scripts/rhel_oval_deprecation.py
This PR is the web-server side of https://github.com/AlmaLinux/build-system/milestone/7.
Resolves the following issues:
* https://github.com/AlmaLinux/build-system/issues/346
* https://github.com/AlmaLinux/build-system/issues/347
* https://github.com/AlmaLinux/build-system/issues/348
* https://github.com/AlmaLinux/build-system/issues/352
* https://github.com/AlmaLinux/build-system/issues/350
* https://github.com/AlmaLinux/build-system/issues/356
> RHEL OVAL deprecation. New errata workflow

- alws/dramatiq/build.py
Resolves: https://github.com/AlmaLinux/build-system/issues/323
> Unset srpm url if all tasks have failed

- alws/crud/build.py
Resolves: https://github.com/AlmaLinux/build-system/issues/375
We have some urls that do not correspond to our query filters and in result we do not get all existing builds
> Fix bug with build search

- alws/alembic/versions/63bc4e0b699f_add_many_to_many_relationship_between_.py
- alws/crud/release.py
- alws/crud/sign_task.py
- alws/middlewares/__init__.py
- alws/middlewares/releases.py
- alws/models.py
- alws/release_planner.py
- alws/routers/releases.py
- alws/utils/pulp_client.py
- reference_data/platforms.yaml
- scripts/exporters/packages_exporter.py
- tests/fixtures/platforms.py
Resolves AlmaLinux/build-system#369:
- For cross-releasing we should include an RPM artifact...
...if the reference platforms of its build task has intersection with...
...the reference platform of base platform which we want to release a build
> Enable cross-releasing between platforms

- alws/crud/errata.py
- alws/routers/errata.py
Fixes: AlmaLinux/build-system#419
> Fix Reset matched packages do not work on advisory with the same ID

- reference_data/platform_flavors.yaml
Required for bootstrapping AlmaLinux Kitten 10 RISC-V against Fedora 40
> Add --nobest when building with Fedora-40-riscv64 flavor

- scripts/exporters/base_exporter.py
- scripts/exporters/packages_exporter.py
- scripts/exporters/products_exporter.py
Resolves: https://github.com/AlmaLinux/build-system/issues/444
> Allow signing repodata while exporting products

- alws/scripts/git_cacher/git_cacher.py
- alws/utils/gitea.py
Resolves: https://github.com/AlmaLinux/build-system/issues/471
> Change endpoint for fetching tags from Gitea API

- alws/build_planner.py
- alws/crud/errata.py
- reference_data/centos_stream.yml
- reference_data/platform_flavors.yaml
- reference_data/platforms.yaml
- scripts/exporters/packages_exporter.py
Resolves: https://github.com/AlmaLinux/build-system/issues/475
> Move platform versions from modularity to data field

- scripts/bs-490-add_x86_64_v2_pkgs_to_errata.py
Fixes: https://github.com/AlmaLinux/build-system/issues/490
> Add script to add x86_64_v2 packages to released erratas

- alws/crud/errata.py
- alws/models.py
- alws/schemas/errata_schema.py
- alws/utils/errata.py
- alws/utils/parsing.py
- alws/utils/pulp_utils.py
* Do not clean the alma suffix from the package release in AlmaLinux erratas to ensure exact nevr mappings
* Approve initial errata package mappings by default
Resolves: https://github.com/AlmaLinux/build-system/issues/492
> Custom handing of errata package mapping for AlmaLinux erratas
